### ISSUE TITLE
other domains

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Castor#1]
currently castor only uses 117 analysis.  (conditions)

What about other domains?

Great tool btw. Thank you for the release.

**Comment by AnthonyMolinaro** [comment]
Hi @vojtechhuser ,

The domains baked into getAchillesMonthlyData, which is called by getAchillesTs, are the following:

Visits, Conditions, Procedures, Drugs, Observations, Measurements, and Devices.  These correspond to analysis_ids 202,402,602,702,802,1802 and 2102, respectively.

Analysis_id 117 is only used to compute the denominator of the prevalence time series.  

The other domains are already there.  : )
