### ISSUE TITLE
Main Branch Name

### ISSUE THREAD

**Issue by BSCrumpton** [OHDSI/Castor#3]
Hey there, was the main branch name recently changed from master to main? 

I've noticed that while installing the Achilles R package from github, it's failing since it default will pull from branch "master". I know the build worked sometime last week- i'm assuming before any changes recently made. 

If it was recently changed- I'm not sure if the better fix is for y'all to change your branch name back, or update the Achilles repo to reference the new branch name.

**Comment by fdefalco** [comment]
Not exactly sure what happened, but the branch has been renamed to master, as it should be named, and that should resolve the issue with the reference.  Thanks for pointing that out.
